"""
Copula Tail-Dependency Analysis
================================
Fits bivariate copulas (Gumbel / Clayton) to key variable pairs,
computes parametric upper- and lower-tail dependence coefficients,
and generates tail-dependence curves.

**Methodological caveat:**  Draws are generated by the deterministic
physics model (not from empirical data).  Tail-dependence estimates
therefore reflect *model-implied* structure rather than observed
empirical co-movement.  Carbon intensity is sampled independently
of temperature and CPU, so CI-related pairs will show near-zero
dependence by construction.  The analysis is useful for stress-testing
the model's joint tails and for motivating future empirical work.

Outputs
-------
- copula_tail_dependence.csv
- copula_tail_curves.csv
- figures/copula_tail_dependence.png
"""

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from scipy import stats
from config import MC, OUTPUT_DIR, FIGURE_DIR, PLOT, DC_PARAMS, GRID, TEMPERATURE, FINANCE

np.random.seed(MC["seed"])


# ── Pair definitions ─────────────────────────────────────────────────────
# Keep only the two non-tautological pairs that reveal genuine risk insight:
#  1. Temperature → Energy: climate-compounding tail risk
#  2. PUE → Total Cost: efficiency-driven cost amplification
PAIRS = [
    ("temperature",    "energy_demand"),
    ("pue",            "total_cost"),
]


# ── Generate correlated draws from the physical model ────────────────────
def _build_dataset(n: int = 20000) -> pd.DataFrame:
    temp_f = np.random.normal(TEMPERATURE["mean_f"], TEMPERATURE["std_f"], n)
    temp_f = np.clip(temp_f, TEMPERATURE["min_f"] - 5, TEMPERATURE["max_f"] + 5)
    cpu = np.random.normal(DC_PARAMS["cpu_utilization_mean"],
                           DC_PARAMS["cpu_utilization_std"], n)
    cpu = np.clip(cpu, 5, 100)
    delta_t = np.maximum(temp_f - 65, 0)
    pue = (DC_PARAMS["pue_baseline"]
           + DC_PARAMS["pue_temp_coef"] * delta_t
           + DC_PARAMS["pue_cpu_coef"] * cpu)
    idle = DC_PARAMS["idle_power_fraction"]
    it_mw = DC_PARAMS["it_capacity_mw"] * (idle + (1 - idle) * cpu / 100)
    total_mw = it_mw * pue
    energy_mwh = total_mw * 8760
    ci = np.random.normal(GRID["carbon_intensity_mean"],
                          GRID["carbon_intensity_std"], n)
    ci = np.clip(ci, GRID["carbon_intensity_min"], GRID["carbon_intensity_max"])
    emissions = total_mw * ci * 8760 / 1000
    total_cost = energy_mwh * FINANCE["energy_price_usd_per_mwh"] + emissions * FINANCE["scc_usd_per_ton"]
    return pd.DataFrame({
        "temperature": temp_f,
        "cpu_utilization": cpu,
        "pue": pue,
        "energy_demand": energy_mwh,
        "carbon_intensity": ci,
        "emissions": emissions,
        "total_cost": total_cost,
    })


# ── Tail-dependence computation ──────────────────────────────────────────
def _empirical_tail_dependence(u, v, thresholds):
    """Compute empirical upper and lower tail dependence at each threshold."""
    upper, lower = [], []
    for t in thresholds:
        # Upper tail:  P(V > t | U > t)
        mask_u = u > t
        if mask_u.sum() > 10:
            upper.append((v[mask_u] > t).mean())
        else:
            upper.append(np.nan)
        # Lower tail:  P(V < 1-t | U < 1-t)
        lt = 1 - t
        mask_l = u < lt
        if mask_l.sum() > 10:
            lower.append((v[mask_l] < lt).mean())
        else:
            lower.append(np.nan)
    return np.array(upper), np.array(lower)


def _rank_transform(x):
    """Convert to pseudo-observations on (0, 1)."""
    n = len(x)
    return stats.rankdata(x) / (n + 1)


def compute_copula_metrics(df: pd.DataFrame):
    thresholds = np.linspace(0.80, 0.995, 50)

    dep_rows = []
    curve_rows = []

    for (var_a, var_b) in PAIRS:
        a, b = df[var_a].values, df[var_b].values
        u, v = _rank_transform(a), _rank_transform(b)

        upper, lower = _empirical_tail_dependence(u, v, thresholds)

        # Kendall tau → parametric copula fit
        tau, _ = stats.kendalltau(a, b)
        tau = np.clip(tau, -0.99, 0.99)

        # Gumbel parameter  (only valid for tau >= 0)
        if tau > 0:
            theta_gumbel = 1 / (1 - tau)
            upper_param = 2 - 2 ** (1 / theta_gumbel)
        else:
            theta_gumbel = 1.0
            upper_param = 0.0

        # Clayton parameter  (only valid for tau > 0)
        if tau > 0:
            theta_clayton = 2 * tau / (1 - tau)
            lower_param = 2 ** (-1 / theta_clayton)
        else:
            theta_clayton = 0.0
            lower_param = 0.0

        pair_label = f"{var_a}_vs_{var_b}"
        dep_rows.append({
            "pair": pair_label,
            "kendall_tau": round(tau, 4),
            "gumbel_theta": round(theta_gumbel, 4),
            "clayton_theta": round(theta_clayton, 4),
            "upper_tail": round(upper_param, 4),
            "lower_tail": round(lower_param, 4),
            "spearman_rho": round(stats.spearmanr(a, b).correlation, 4),
        })

        for t, up, lo in zip(thresholds, upper, lower):
            curve_rows.append({
                "pair": pair_label,
                "threshold": round(t, 4),
                "upper_tail_empirical": round(up, 4) if not np.isnan(up) else None,
                "lower_tail_empirical": round(lo, 4) if not np.isnan(lo) else None,
            })

    dep_df = pd.DataFrame(dep_rows)
    curve_df = pd.DataFrame(curve_rows)
    return dep_df, curve_df


# ── Figure ───────────────────────────────────────────────────────────────
def plot_tail_dependence(dep_df: pd.DataFrame, curve_df: pd.DataFrame):
    """Clean 1×2 panel: Temperature→Energy (climate risk) and PUE→Cost (efficiency risk)."""
    n_pairs = len(PAIRS)
    fig, axes = plt.subplots(1, n_pairs, figsize=(6 * n_pairs, 5))
    if n_pairs == 1:
        axes = [axes]

    nice_titles = {
        "temperature_vs_energy_demand": "Temperature → Energy Demand\n(Climate-Compounding Tail Risk)",
        "pue_vs_total_cost": "PUE → Total Cost\n(Efficiency-Driven Cost Amplification)",
    }

    for i, (var_a, var_b) in enumerate(PAIRS):
        ax = axes[i]
        pair_label = f"{var_a}_vs_{var_b}"
        sub = curve_df[curve_df["pair"] == pair_label]
        thresholds = sub["threshold"].values
        upper = sub["upper_tail_empirical"].values.astype(float)
        lower = sub["lower_tail_empirical"].values.astype(float)

        ax.plot(thresholds, upper, color="#e74c3c", lw=2.5, label="Upper tail λ_U")
        ax.plot(thresholds, lower, color="#2980b9", lw=2.5, label="Lower tail λ_L")

        # Approximate 95% CI band (binomial: sqrt(p(1-p)/n_eff))
        n_eff = 20000 * (1 - thresholds)
        n_eff = np.clip(n_eff, 10, None)
        for vals, c in [(upper, "#e74c3c"), (lower, "#2980b9")]:
            se = np.sqrt(np.clip(vals * (1 - vals), 0, None) / n_eff)
            ax.fill_between(thresholds, vals - 1.96*se, vals + 1.96*se, alpha=0.12, color=c)

        # Parametric reference lines
        row = dep_df[dep_df["pair"] == pair_label].iloc[0]
        ax.axhline(row["upper_tail"], color="#e74c3c", ls="--", alpha=0.5,
                   label=f"Gumbel λ_U = {row['upper_tail']:.3f}")
        ax.axhline(row["lower_tail"], color="#2980b9", ls="--", alpha=0.5,
                   label=f"Clayton λ_L = {row['lower_tail']:.3f}")

        ax.set_title(nice_titles.get(pair_label, pair_label.replace("_", " ").title()),
                     fontsize=12, fontweight="bold")
        ax.set_xlabel("Threshold quantile", fontsize=11)
        ax.set_ylabel("Tail dependence", fontsize=11)

        max_val = max(np.nanmax(upper), np.nanmax(lower),
                      row["upper_tail"], row["lower_tail"], 0.05)
        ax.set_ylim(-0.02, max(max_val * 1.4, 0.1))
        ax.legend(fontsize=8, loc="upper right")

        # Kendall tau annotation
        ax.text(0.05, 0.95, f"τ = {row['kendall_tau']:.3f}",
                transform=ax.transAxes, fontsize=10, va="top",
                bbox=dict(boxstyle="round,pad=0.3", facecolor="lightyellow", alpha=0.85))

    fig.suptitle("Copula Tail Dependence – Key Risk Pairs\n"
                 "(Model-implied; bands = 95% binomial CI)",
                 fontsize=14, fontweight="bold", y=1.03)
    plt.tight_layout()
    fig.savefig(FIGURE_DIR / "copula_tail_dependence.png", dpi=PLOT["dpi"], bbox_inches="tight")
    plt.close()


# ── Entry Point ──────────────────────────────────────────────────────────
def run():
    print("  ▶ Running copula tail-dependency analysis …")
    df = _build_dataset()
    dep_df, curve_df = compute_copula_metrics(df)

    dep_df.to_csv(OUTPUT_DIR / "copula_tail_dependence.csv", index=False)
    curve_df.to_csv(OUTPUT_DIR / "copula_tail_curves.csv", index=False)

    plot_tail_dependence(dep_df, curve_df)

    # Remove stale scatter matrix if it exists from prior runs
    scatter_path = FIGURE_DIR / "copula_scatter_matrix.png"
    if scatter_path.exists():
        scatter_path.unlink()

    print(f"    ✓ {len(PAIRS)} pairs analysed")
    for _, r in dep_df.iterrows():
        print(f"      {r['pair']:30s}  τ={r['kendall_tau']:+.3f}  λ_U={r['upper_tail']:.3f}  λ_L={r['lower_tail']:.3f}")
    return dep_df, curve_df


if __name__ == "__main__":
    run()
